### ISSUE TITLE
Sharing function names

### ISSUE THREAD

**Issue by zanderdk** [kakaroto/ipclib#1]
Hi, 
Any chance you could sare you rev progress? struct definitions and function names. Im intrested in bub and syslib probably some kernel  as well. Could you export a map file from ida?

Thx.

**Comment by zanderdk** [comment]
Im mostly intrested in CSE for TXE 3.0.1.1107.

**Comment by kakaroto** [comment]
This is all I have. I haven't touched this in 4 years, and barely even remembered this project.
I don't have IDA installed anymore, so unfortunately, can't help further.
